repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v15.0.7
  hooks:
  - id: clang-format
    types_or: [c++, c]
    exclude: |
      (?x)(
        ^common/catch2/|
        ^common/logc/|
        ^device/sdk/|
        ^hardware/
      )
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.9
      args:
        - --line-length=120

